// System call numbers
#define SYS_fork   1
#define SYS_exit   2
#define SYS_wait   3
#define SYS_pipe   4
#define SYS_read   5
#define SYS_kill   6
#define SYS_exec   7
#define SYS_fstat  8
#define SYS_chdir  9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_pause  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21
#define SYS_agent_fork 22
#define SYS_agent_info 23
#define SYS_agent_call 24
#define SYS_agent_tool_list 25
#define SYS_tool_call 26
#define SYS_tool_list 27
#define SYS_agent_create 28
#define SYS_context_push 29
#define SYS_context_query 30
#define SYS_context_rollback 31
#define SYS_context_clear 32
#define SYS_agent_run 33
#define SYS_context_snapshot 34
