#ifndef EXEC_POLICY_MANIFEST_H
#define EXEC_POLICY_MANIFEST_H

/*
 * 构建期可执行文件信任策略。主机 mkfs 按全部条目配置不可变 inode 元数据，
 * 用户态启动器复用同表，避免可执行别名、角色和安全配置漂移。
 */
#define EXEC_MANIFEST_VERSION 2U

#define EXEC_MANIFEST_F_TRUSTED     0x1U
#define EXEC_MANIFEST_F_IMMUTABLE   0x2U
#define EXEC_MANIFEST_F_BOOTSTRAP   0x4U
#define EXEC_MANIFEST_F_DOMAIN_SAFE 0x8U

#define EXEC_MANIFEST_F_SEALED \
	(EXEC_MANIFEST_F_TRUSTED | EXEC_MANIFEST_F_IMMUTABLE | \
	 EXEC_MANIFEST_F_DOMAIN_SAFE)
#define EXEC_MANIFEST_F_BOOT_SEALED \
	(EXEC_MANIFEST_F_SEALED | EXEC_MANIFEST_F_BOOTSTRAP)

#define EXEC_MANIFEST_ROLE_SENTINEL     1
#define EXEC_MANIFEST_ROLE_INVESTIGATOR 2
#define EXEC_MANIFEST_ROLE_RECOVERY     3
#define EXEC_MANIFEST_ROLE_ORCHESTRATOR 4
#define EXEC_MANIFEST_ROLE_ARTIFACT     5
#define EXEC_MANIFEST_ROLE_BIT(role) (1U << (role))
#define EXEC_MANIFEST_ROLE_ALL 0x3eU

/* 可执行文件安全配置只设上限，不产生权限。 */
#define EXEC_MANIFEST_VFS_PROFILE_NONE     0U
#define EXEC_MANIFEST_VFS_PROFILE_WORKFLOW 1U
#define EXEC_MANIFEST_VFS_PROFILE_CONTENT_READ 2U
#define EXEC_MANIFEST_VFS_PROFILE_ARTIFACT_WRITE 3U

/* 与 Agent 能力命名空间保持一致。 */
#define EXEC_MANIFEST_VFS_CONTENT_READ   (1ULL << 1)
#define EXEC_MANIFEST_VFS_ARTIFACT_WRITE (1ULL << 6)
#define EXEC_MANIFEST_VFS_WORKFLOW_CAPS \
	(EXEC_MANIFEST_VFS_CONTENT_READ | EXEC_MANIFEST_VFS_ARTIFACT_WRITE)

/*
 * 非 Agent 工作进程使用完整源码名派生的确定性封装别名；mkfs 拒绝哈希冲突，
 * 避免 DIRSIZ 截断误选映像。
 */
static inline unsigned int exec_manifest_name_hash(const char *name)
{
	unsigned int hash = 2166136261U;

	for (; name != 0 && *name != 0; name++) {
		hash ^= (unsigned char)*name;
		hash *= 16777619U;
	}
	return hash;
}

static inline void exec_manifest_worker_image(const char *source,
					       char image[11])
{
	static const char hex[] = "0123456789abcdef";
	unsigned int hash = exec_manifest_name_hash(source);

	image[0] = 'w';
	image[1] = 'x';
	for (int i = 0; i < 8; i++)
		image[2 + i] = hex[(hash >> (28 - i * 4)) & 0xfU];
	image[10] = 0;
}

/*
 * X(源二进制、安装映像、标志、允许角色掩码、启动角色、可执行安全配置)
 * 安装映像不同时创建封装代码别名，并保留源码名作为公开兼容映像；
 * 不由 rp_orch 以 Agent 启动的条目，其启动角色为零。
 */
#define EXEC_POLICY_ENTRIES(X) \
	X("usershell", "usershell", EXEC_MANIFEST_F_SEALED, 0, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_NONE) \
	X("agentfinal_ucore", "agentfinal_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, EXEC_MANIFEST_ROLE_ALL, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("agentfs_ucore", "agentfs_ucore", EXEC_MANIFEST_F_BOOT_SEALED, \
	  EXEC_MANIFEST_ROLE_ALL, 0, EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("agentscan_ucore", "agentscan_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, EXEC_MANIFEST_ROLE_ALL, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("agentloop_ucore", "agentloop_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, EXEC_MANIFEST_ROLE_ALL, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("agentsched_ucore", "agentsched_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, EXEC_MANIFEST_ROLE_ALL, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("agentconflict_ucore", "agentconflict_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, EXEC_MANIFEST_ROLE_ALL, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("agentllm_ucore", "agentllm_ucore", EXEC_MANIFEST_F_BOOT_SEALED, \
	  EXEC_MANIFEST_ROLE_ALL, 0, EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("agentlive_ucore", "agentlive_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ORCHESTRATOR), 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("agentnexus_ucore", "agentnexus_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ORCHESTRATOR) | \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_SENTINEL) | \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_INVESTIGATOR) | \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ARTIFACT), 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("agentbench_ucore", "agentbench_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, EXEC_MANIFEST_ROLE_ALL, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("agentcontract_ucore", "agentcontract_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ORCHESTRATOR) | \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_SENTINEL), 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("agent_eevdf_ucore", "agent_eevdf_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ORCHESTRATOR), 0, \
	  EXEC_MANIFEST_VFS_PROFILE_CONTENT_READ) \
	X("agenttask_ucore", "agenttask_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ORCHESTRATOR), 0, \
	  EXEC_MANIFEST_VFS_PROFILE_CONTENT_READ) \
	X("agenteval_ucore", "agenteval_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ORCHESTRATOR) | \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_SENTINEL), 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("labdemo_ucore", "labdemo_ucore", EXEC_MANIFEST_F_BOOT_SEALED, \
	  EXEC_MANIFEST_ROLE_ALL, 0, EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("labdemo_execprobe_ucore", "ldexecprobe", \
	  EXEC_MANIFEST_F_SEALED, 0, 0, EXEC_MANIFEST_VFS_PROFILE_NONE) \
	X("agentsecurity_ucore", "agentsecurity_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, EXEC_MANIFEST_ROLE_ALL, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("agenttoolabi_ucore", "agenttoolabi_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, EXEC_MANIFEST_ROLE_ALL, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("agentscope_ucore", "agentscope_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, EXEC_MANIFEST_ROLE_ALL, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("workflow_teardown_race_ucore", "workflow_teardown_race_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, EXEC_MANIFEST_ROLE_ALL, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("workflow_teardown_race_ucore", "wf_public", \
	  EXEC_MANIFEST_F_SEALED, EXEC_MANIFEST_ROLE_ALL, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_NONE) \
	X("iobudget_ucore", "iobudget_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, EXEC_MANIFEST_ROLE_ALL, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("agenttrust_ucore", "agenttrust_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ORCHESTRATOR), 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("agenttrust_ucore", "at_orch", EXEC_MANIFEST_F_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ORCHESTRATOR), 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("agenttrust_ucore", "at_sentinel", EXEC_MANIFEST_F_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_SENTINEL), 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("agentvfs_ucore", "agentvfs_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, EXEC_MANIFEST_ROLE_ALL, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("agentvfs_probe", "vfs_reader", EXEC_MANIFEST_F_SEALED, 0, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_CONTENT_READ) \
	X("agentvfs_probe", "vfs_writer", EXEC_MANIFEST_F_SEALED, 0, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_ARTIFACT_WRITE) \
	X("fsquota_ucore", "fsquota_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, EXEC_MANIFEST_ROLE_ALL, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("fspquota_ucore", "fspquota_ucore", EXEC_MANIFEST_F_SEALED, 0, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_NONE) \
	X("procreap_agent_ucore", "procreap_agent_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, EXEC_MANIFEST_ROLE_ALL, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("fileresource_ucore", "fileresource_ucore", \
	  EXEC_MANIFEST_F_SEALED, 0, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_NONE) \
	X("threadresource_ucore", "threadresource_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, EXEC_MANIFEST_ROLE_ALL, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("physicalresource_ucore", "physicalresource_ucore", \
	  EXEC_MANIFEST_F_BOOT_SEALED, EXEC_MANIFEST_ROLE_ALL, 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("rp_agentos_orch", "rp_agentos_orch", \
	  EXEC_MANIFEST_F_BOOT_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ORCHESTRATOR), 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("rp_resource_probe", "rp_resprobe", EXEC_MANIFEST_F_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ORCHESTRATOR) | \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ARTIFACT), 0, \
	  EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("rp_orch", "rp_orch", EXEC_MANIFEST_F_SEALED, \
	  EXEC_MANIFEST_ROLE_ALL, 0, EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("rp_query", "ax_query", EXEC_MANIFEST_F_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ARTIFACT), \
	  EXEC_MANIFEST_ROLE_ARTIFACT, EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("rp_repair", "ax_repair", EXEC_MANIFEST_F_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_RECOVERY), \
	  EXEC_MANIFEST_ROLE_RECOVERY, EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("rp_execobs", "ax_execobs", EXEC_MANIFEST_F_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ARTIFACT), \
	  EXEC_MANIFEST_ROLE_ARTIFACT, EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("rp_agent_collab", "ax_collab", EXEC_MANIFEST_F_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ORCHESTRATOR) | \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_SENTINEL), \
	  EXEC_MANIFEST_ROLE_ORCHESTRATOR, EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("rp_auditor", "ax_auditor", EXEC_MANIFEST_F_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ORCHESTRATOR), \
	  EXEC_MANIFEST_ROLE_ORCHESTRATOR, EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("rp_workbench", "ax_workbench", EXEC_MANIFEST_F_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ARTIFACT), \
	  EXEC_MANIFEST_ROLE_ARTIFACT, EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("rp_package", "ax_package", EXEC_MANIFEST_F_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ORCHESTRATOR), \
	  EXEC_MANIFEST_ROLE_ORCHESTRATOR, EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("rp_realtask", "ax_realtask", EXEC_MANIFEST_F_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ORCHESTRATOR), \
	  EXEC_MANIFEST_ROLE_ORCHESTRATOR, EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("rp_service_surface", "ax_service", EXEC_MANIFEST_F_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ARTIFACT), \
	  EXEC_MANIFEST_ROLE_ARTIFACT, EXEC_MANIFEST_VFS_PROFILE_WORKFLOW) \
	X("rp_backend", "ax_backend", EXEC_MANIFEST_F_SEALED, \
	  EXEC_MANIFEST_ROLE_BIT(EXEC_MANIFEST_ROLE_ORCHESTRATOR), \
	  EXEC_MANIFEST_ROLE_ORCHESTRATOR, EXEC_MANIFEST_VFS_PROFILE_WORKFLOW)

#endif
