#include <stdio.h>
#define RP_ENABLE_HOST_ACTION_SEED 1
#include <research_platform_state.h>

int main(void)
{
	if (!rp_file_contains("rp_fix", "status=recovered")) return 1;
	if (!rp_file_contains("rp_release", "decision=release")) return 1;
	if (!rp_file_contains("rp_wfio", "compatibility_checks=6")) return 1;
	if (!rp_file_contains("rp_wfio", "package=workflow-portability")) return 1;
	if (!rp_file_contains("rp_wfio", "migration_steps=9")) return 1;
	if (!rp_file_contains("rp_review2", "rounds=2")) return 1;
	if (!rp_file_contains("rp_review2", "review_threads=2")) return 1;
	if (!rp_file_contains("rp_review2", "action_items=2")) return 1;
	if (!rp_file_contains("rp_revision", "draft_versions=3")) return 1;
	if (!rp_file_contains("rp_dataver", "release_candidate=v2")) return 1;
	if (!rp_file_contains("rp_repro", "status=ready")) return 1;
	if (!rp_file_contains("rp_claimrec", "claim=8")) return 1;
	if (!rp_file_contains("rp_provpath", "critical_paths=3")) return 1;
	if (!rp_file_contains("rp_dataprof", "profiles=4")) return 1;
	if (!rp_file_contains("rp_figrec", "exported=3")) return 1;
	if (!rp_file_contains("rp_trialrec", "selected=trial-3")) return 1;
	if (!rp_file_contains("rp_risk", "open_risks=0")) return 1;
	if (!rp_file_contains("rp_capa", "verifications=2")) return 1;
	if (!rp_file_contains("rp_risk", "decision_support=decision:agentos-final-demo-backend")) return 1;
	if (!rp_file_contains("rp_protocol", "protocol_compliance_reports=1")) return 1;
	if (!rp_file_contains("rp_protocol", "protocol_amendments=1")) return 1;
	if (!rp_file_contains("rp_soplog", "sop_executions=1")) return 1;
	if (!rp_file_contains("rp_sched", "queue_items=21")) return 1;
	if (!rp_file_contains("rp_taskrec", "class=critical")) return 1;
	if (!rp_file_contains("rp_rank", "selected=10")) return 1;
	if (!rp_file_contains("rp_budget", "decision=within_budget")) return 1;
	if (!rp_file_contains("rp_retrylog", "attempts=2")) return 1;
	if (!rp_file_contains("rp_runview", "status=ready")) return 1;
	if (!rp_file_contains("rp_query", "knowledge_index=search_documents:1685")) return 1;
	if (!rp_file_contains("rp_query", "provenance_nodes:406")) return 1;
	if (!rp_file_contains("rp_query", "provenance_links:544")) return 1;
	if (!rp_file_contains("rp_query", "events:8966")) return 1;
	if (!rp_file_contains("rp_query", "context_records:380")) return 1;
	if (!rp_file_contains("rp_llmlog", "transcripts=99")) return 1;
	if (!rp_file_contains("rp_llmlog", "bridge_requests=33")) return 1;
	if (!rp_file_contains("rp_llmlog", "bridge_responses=33")) return 1;
	if (!rp_file_contains("rp_runner", "workbench_delivery_scale=workbenches:8")) return 1;
	if (!rp_file_contains("rp_runner", "deliveries:9")) return 1;
	if (!rp_file_contains("rp_runner", "project_action_plans:17")) return 1;
	if (!rp_file_contains("rp_runner", "project_runbooks:17")) return 1;
	if (!rp_file_contains("rp_fail", "recoverable=1")) return 1;
	if (!rp_file_contains("rp_relay", "status=ready")) return 1;
	if (!rp_file_contains("rp_relay", "relay_packets=3")) return 1;
	if (!rp_file_contains("rp_llm_packets", "packets=3")) return 1;
	if (!rp_file_contains("rp_llm_routes", "routes=4")) return 1;
	if (!rp_file_contains("rp_llm_guard", "secrets_in_ucore=0")) return 1;
	if (!rp_file_contains("rp_llm_hostreq", "cloud_mode=optional_host_side")) return 1;
	if (!rp_file_contains("rp_llm_fallback", "fallback_cases=1")) return 1;
	if (!rp_file_contains("rp_prompt", "routes=4")) return 1;
	if (!rp_file_contains("rp_llmq", "queued=3")) return 1;
	if (!rp_file_contains("rp_llmeval", "passed=7")) return 1;
	if (!rp_file_contains("rp_llmlog", "request_packets=3")) return 1;
	if (!rp_file_contains("rp_policy", "access_profiles=4")) return 1;
	if (!rp_file_contains("rp_compliance", "relay_protocol_files=5")) return 1;
	if (!rp_file_contains("rp_compliance", "decision=accepted")) return 1;
	if (!rp_file_contains("rp_delta", "items=20")) return 1;
	if (!rp_file_contains("rp_diff", "changed_items=20")) return 1;
	if (!rp_file_contains("rp_execobs", "timeline_events=9")) return 1;
	if (!rp_file_contains("rp_worker", "heartbeats=4")) return 1;
	if (!rp_file_contains("rp_runconf", "profiles=2")) return 1;
	if (!rp_file_contains("rp_configdrift", "changed_parameters=2")) return 1;
	if (!rp_file_contains("rp_invocation", "steps=10")) return 1;
	if (!rp_file_contains("rp_completion", "actions=4")) return 1;
	if (!rp_file_contains("rp_runner", "stages=5")) return 1;
	if (!rp_file_contains("rp_runner", "workbench_tasks=9")) return 1;
	if (!rp_file_contains("rp_input", "dynamic_submissions=4")) return 1;
	if (!rp_file_contains("rp_runner", "dynamic_input_runs=4")) return 1;
	if (!rp_file_contains("rp_stage_state", "stages=5")) return 1;
	if (!rp_file_contains("rp_cache_index", "cache_hits=1")) return 1;
	if (!rp_file_contains("rp_retry_plan", "retry_items=1")) return 1;
	if (!rp_file_contains("rp_run_events", "events=8")) return 1;
	if (!rp_file_contains("rp_artifact_manifest", "manifest_records=4")) return 1;
	if (!rp_file_contains("rp_artifact", "status=recovered")) return 1;
	if (!rp_file_contains("rp_chart_data", "status=ready")) return 1;
	if (!rp_file_contains("rp_ingest_files", "files=2")) return 1;
	if (!rp_file_contains("rp_dataset_snapshot", "snapshots=2")) return 1;
	if (!rp_file_contains("rp_data_preview", "previews=2")) return 1;
	if (!rp_file_contains("rp_data_quality", "passed=7")) return 1;
	if (!rp_file_contains("rp_data_transform", "transforms=2")) return 1;
	if (!rp_file_contains("rp_dataset_collection", "items=4")) return 1;
	if (!rp_file_contains("rp_agents", "agents=7")) return 1;
	if (!rp_file_contains("rp_decisions", "decisions=8")) return 1;
	if (!rp_file_contains("rp_handoff", "handoffs=6")) return 1;
	if (!rp_file_contains("rp_agent_run", "agent_messages=21")) return 1;
	if (!rp_file_contains("rp_backend", "cases=7")) return 1;
	if (!rp_file_contains("rp_backend", "agentos_mainflow_kernel=required")) return 1;
	if (!rp_file_contains("rp_agentos_recovery", "kernel_tool=rerun_stage,write_report")) return 1;
	if (!rp_file_contains("rp_agentos_query", "metadata_source=kernel_file_index")) return 1;
	if (!rp_file_contains("rp_agentos_timeline", "event_delivery=kernel_agent_queue")) return 1;
	if (!rp_file_contains("rp_agentos_audit", "audit_source=kernel_ledger")) return 1;
	if (!rp_file_contains("rp_consistency", "state_relation=passed")) return 1;
	if (!rp_file_contains("rp_consistency", "coherence_checks=9")) return 1;
	if (!rp_file_contains("rp_sreg", "samples=8")) return 1;
	if (!rp_file_contains("rp_instr", "instruments=4")) return 1;
	if (!rp_file_contains("rp_labresop", "lab_governance_ops=approvals:2")) return 1;
	if (!rp_file_contains("rp_labresop", "protocol_compliance_reports:2")) return 1;
	if (!rp_file_contains("rp_labresop", "sop_executions:3")) return 1;
	if (!rp_file_contains("rp_labresop", "training_records:4")) return 1;
	if (!rp_file_contains("rp_labresop", "notifications:3")) return 1;
	if (!rp_file_contains("rp_resrev", "review_items=10")) return 1;
	if (!rp_file_contains("rp_semindex", "documents=17")) return 1;
	if (!rp_file_contains("rp_runenv", "environments=4")) return 1;
	if (!rp_file_contains("rp_mail", "to=metrics")) return 1;
	if (!rp_file_contains("rp_nbexec", "notebook=reproducible-analysis.ipynb")) return 1;
	if (!rp_file_contains("rp_repro", "downloadable_units=4")) return 1;
	if (!rp_file_contains("rp_runop", "advanced_surface=objects:5")) return 1;
	if (!rp_file_contains("rp_runop", "research_search:saved_queries:2")) return 1;
	if (!rp_file_contains("rp_runop", "project_space:lab-gene-x")) return 1;
	if (!rp_file_contains("rp_runop", "study_protocol:protocols:2")) return 1;
	if (!rp_file_contains("rp_runop", "dataset_answer:datasets:2")) return 1;
	if (!rp_file_contains("rp_runop", "package_intake:packages:1")) return 1;
	if (!rp_file_contains("rp_runop", "agentos_advanced_surface=kernel_bound")) return 1;
	if (!rp_file_contains("rp_runop", "agentos_advanced_surface_detail=tool:echo,tool:read_context")) return 1;
	if (!rp_file_contains("rp_runop", "startup_health=quickstart:ready")) return 1;
	if (!rp_file_contains("rp_runop", "configuration_health=settings:ready")) return 1;
	if (!rp_file_contains("rp_runop", "platform_doctor=ready;checks=10")) return 1;
	if (!rp_file_contains("rp_startup", "quickstart=ready")) return 1;
	if (!rp_file_contains("rp_startup", "doctor_checks=10")) return 1;
	if (!rp_file_contains("rp_startup", "recommended_commands=startup_guide")) return 1;
	if (!rp_file_contains("rp_runop", "project_scaffold=templates:3")) return 1;
	if (!rp_file_contains("rp_runop", "dataset_product=previews:2")) return 1;
	if (!rp_file_contains("rp_runop", "source_portfolio=sources:67")) return 1;
	if (!rp_file_contains("rp_runop", "research_portfolio_scale=sources:67")) return 1;
	if (!rp_file_contains("rp_runop", "datasets:5")) return 1;
	if (!rp_file_contains("rp_runop", "doctor_reports:12")) return 1;
	if (!rp_file_contains("rp_runop", "project_handoff_audits:34")) return 1;
	if (!rp_file_contains("rp_runop", "project_run_comparisons:17")) return 1;
	if (!rp_file_contains("rp_runop", "project_reproducibility_audits:17")) return 1;
	if (!rp_file_contains("rp_runop", "project_snapshot_comparisons:17")) return 1;
	if (!rp_file_contains("rp_runop", "study_protocol_reproduction=packages:1")) return 1;
	if (!rp_file_contains("rp_runop", "project_bundle_cache=latest:ready")) return 1;
	if (!rp_file_contains("rp_runop", "runtime_assurance=secret_refs:3")) return 1;
	if (!rp_file_contains("rp_runop", "llm_proxy_audits:2")) return 1;
	if (!rp_file_contains("rp_runop", "research_ops=semantic_entities:8")) return 1;
	if (!rp_file_contains("rp_runop", "prompt_templates:2")) return 1;
	if (!rp_file_contains("rp_runop", "runbook_steps:7")) return 1;
	if (!rp_file_contains("rp_runop", "worker_ops:6")) return 1;
	if (!rp_file_contains("rp_runop", "execution_controls:8")) return 1;
	if (!rp_file_contains("rp_runop", "regulated_research=annotation_schemas:1")) return 1;
	if (!rp_file_contains("rp_runop", "assay_plates:1")) return 1;
	if (!rp_file_contains("rp_runop", "data_access_requests:1")) return 1;
	if (!rp_file_contains("rp_runop", "research_object_crates:1")) return 1;
	if (!rp_file_contains("rp_runop", "workflow_templates:8")) return 1;
	int ack_count = rp_count_lines("rp_ack");
	int tool_count = rp_count_lines("rp_tool");
	if (ack_count < 27 || tool_count < 113) return 1;
	if (!rp_write_file("rp_telemetry",
			   "run_id=RUN-042\n"
			   "status=ready\n"
			   "trace_spans=8\n"
			   "bottlenecks=1\n"
			   "message_acks=35\n"
			   "tool_events=115\n"
			   "scheduler_items=21\n"
			   "ranked_tasks=21\n"
			   "selected_tasks=10\n"
			   "policy_checks=8\n"
			   "compliance=accepted\n"
			   "risk_items=3\n"
			   "capa_actions=2\n"
			   "risk_mitigations=3\n"
			   "risk_reviews=1\n"
			   "capa_verifications=2\n"
			   "protocol_compliance_reports=1\n"
			   "protocol_compliance_findings=3\n"
			   "protocol_amendments=1\n"
			   "sop_executions=1\n"
			   "decision_support_packets=1\n"
			   "delta_items=20\n"
			   "diff_records=1\n"
			   "timeline_events=9\n"
			   "worker_heartbeats=4\n"
			   "control_actions=8\n"
			   "run_config_profiles=2\n"
			   "workflow_invocations=1\n"
			   "workflow_attempts=12\n"
			   "completion_actions=4\n"
			   "consistency_checks=420\n"
			   "state_catalog_checks=12\n"
			   "startup_doctor_checks=14\n"
			   "host_state_keys=574\n"
			   "agentos_reserved_surface_checks=21\n"
			   "agentos_reserved_surface=profiles:0,skills:0,tasks:0,deliberations:0,handoffs:0,coord:0,abi:0,adapter:0,readiness:0,tool_bindings:0\n"
			   "knowledge_index_checks=22\n"
			   "llm_transcript_checks=3\n"
			   "llm_bridge_transcripts=99\n"
			   "llm_bridge_requests=33\n"
			   "llm_bridge_responses=33\n"
			   "workbench_delivery_checks=15\n"
			   "usable_research_workbenches=8\n"
			   "usable_research_templates=8\n"
			   "usable_research_workspace_imports=9\n"
			   "usable_research_workspace_inspections=9\n"
			   "usable_research_workbench_answers=11\n"
			   "usable_research_deliveries=9\n"
			   "usable_research_studio_sessions=2\n"
			   "usable_research_project_action_plans=17\n"
			   "usable_research_project_deliveries=4\n"
			   "usable_research_project_runbooks=17\n"
			   "usable_research_project_evidence_audits=17\n"
			   "usable_research_project_provenance_graphs=4\n"
			   "usable_research_project_launches=3\n"
			   "usable_research_project_release_gates=17\n"
			   "usable_research_project_snapshots=17\n"
			   "search_documents=1685\n"
			   "provenance_nodes=406\n"
			   "provenance_links=544\n"
			   "event_stream_records=8966\n"
			   "context_records=380\n"
			   "host_workflow_artifacts=150\n"
			   "usable_research_artifacts=507\n"
			   "usable_research_runs=23\n"
			   "usable_research_stages=197\n"
			   "usable_research_messages=265\n"
			   "usable_research_decisions=242\n"
			   "coherence_checks=9\n"
			   "namespace_checks=12\n"
			   "surface_checks=13\n"
			   "status_semantics=11\n"
			   "reference_checks=18\n"
			   "evidence_trace_checks=14\n"
			   "run_state_checks=9\n"
			   "lifecycle_checks=10\n"
			   "delivery_coherence=3\n"
			   "agentos_readiness_checks=7\n"
			   "runner_stages=5\n"
			   "runner_retries=1\n"
			   "runner_cache_hits=1\n"
			   "workflow_runner_files=5\n"
			   "workflow_events=8\n"
			   "workflow_manifest_records=4\n"
			   "workbench_records=10\n"
			   "workbench_tasks=9\n"
			   "dynamic_input_records=8\n"
			   "dynamic_submissions=4\n"
			   "host_ui_events=10\n"
			   "artifact_records=2\n"
			   "data_pipeline_files=6\n"
			   "dataset_snapshots=2\n"
			   "data_previews=2\n"
			   "data_quality_checks=7\n"
			   "data_transforms=2\n"
			   "dataset_collection_items=4\n"
			   "relay_protocol_files=5\n"
			   "relay_routes=4\n"
			   "host_request_files=1\n"
			   "fallback_cases=1\n"
			   "agent_roles=7\n"
			   "collaboration_decisions=8\n"
			   "handoffs=6\n"
			   "deliberation_items=5\n"
			   "backend_cases=7\n"
			   "bio_service_files=5\n"
			   "bio_samples=8\n"
			   "bio_aliquots=12\n"
			   "lab_resource_files=5\n"
			   "lab_governance_ops_checks=26\n"
			   "approval_checks=2\n"
			   "ethics_protocol_checks=1\n"
			   "protocol_governance_checks=4\n"
			   "sop_execution_checks=3\n"
			   "training_record_checks=4\n"
			   "instrument_maintenance_checks=3\n"
			   "inventory_transaction_checks=3\n"
			   "procurement_order_checks=2\n"
			   "resource_budget_checks=2\n"
			   "run_queue_checks=1\n"
			   "notification_checks=1\n"
			   "instrument_count=4\n"
			   "inventory_items=9\n"
			   "publication_service_files=5\n"
			   "result_review_items=10\n"
			   "fair_checks=8\n"
			   "knowledge_service_files=5\n"
			   "semantic_documents=17\n"
			   "knowledge_answers=4\n"
			   "runtime_service_files=5\n"
			   "runtime_envs=4\n"
			   "notebook_cells=8\n"
			   "notebook_exports=2\n"
			   "downloadable_units=4\n"
			   "advanced_surface_objects=5\n"
			   "startup_checks=8\n"
			   "configuration_health=ready\n"
			   "platform_doctor_checks=10\n"
			   "secret_values_written=0\n"
			   "runtime_assurance_checks=24\n"
			   "secret_reference_checks=6\n"
			   "model_registry_checks=5\n"
			   "llm_proxy_replay_audits=2\n"
			   "collaboration_threads=2\n"
			   "collaboration_action_items=2\n"
			   "observability_alerts=5\n"
			   "observability_health_reports=1\n"
			   "research_ops_checks=28\n"
			   "semantic_graph_checks=6\n"
			   "prompt_ops_checks=5\n"
			   "runbook_checks=7\n"
			   "worker_ops_checks=5\n"
			   "execution_control_checks=5\n"
			   "regulated_research_checks=32\n"
			   "annotation_checks=5\n"
			   "assay_plate_checks=4\n"
			   "cohort_monitoring_checks=3\n"
			   "data_access_checks=4\n"
			   "research_card_checks=4\n"
			   "research_object_checks=5\n"
			   "sample_custody_checks=3\n"
			   "statistical_design_checks=2\n"
			   "workflow_template_checks=2\n"
			   "research_product_checks=18\n"
			   "project_scaffold_files=8\n"
			   "dataset_product_exports=9\n"
			   "dataset_product_runs=2\n"
			   "source_portfolio_exports=1\n"
			   "research_portfolio_checks=16\n"
			   "usable_research_sources=67\n"
			   "usable_research_datasets=5\n"
			   "usable_research_literature_searches=7\n"
			   "usable_research_reviews=11\n"
			   "usable_research_evidence_reviews=7\n"
			   "usable_research_evidence_extractions=25\n"
			   "usable_research_screening_decisions=25\n"
			   "usable_research_exports=80\n"
			   "usable_research_platform_doctor_reports=12\n"
			   "usable_research_project_handoff_audits=34\n"
			   "usable_research_project_run_comparisons=17\n"
			   "usable_research_project_reproducibility_audits=17\n"
			   "usable_research_project_snapshot_comparisons=17\n"
			   "execution_scale_checks=14\n"
			   "host_workflow_runs=10\n"
			   "host_workflow_stage_runs=70\n"
			   "host_workflow_cache=6\n"
			   "host_agent_messages=70\n"
			   "host_agent_decisions=70\n"
			   "agentcompare_reports=4\n"
			   "agentcompare_results=20\n"
			   "agentcompare_profiles=1\n"
			   "content_objects=129\n"
			   "object_references=129\n"
			   "operations_scale_checks=12\n"
			   "host_audit_records=5\n"
			   "host_metrics=13\n"
			   "host_llm_providers=3\n"
			   "host_secret_references=3\n"
			   "host_executed_corr_ids=4\n"
			   "usable_research_projects=23\n"
			   "host_artifacts=128\n"
			   "host_messages=70\n"
			   "host_content_objects=129\n"
			   "host_object_references=129\n"
			   "host_agentcompare_reports=4\n"
			   "host_agentcompare_results=20\n"
               "project_revision_incident_checks=12\n"
               "usable_research_revision_tasks=1\n"
               "usable_research_project_scaffolds=1\n"
               "incidents=1\n"
               "incident_id=INC-RUN-042-ALIGN-OOM\n"
               "incident_failed_stage=align\n"
               "incident_reason=memory_limit\n"
               "incident_status=closed\n"
               "revision_task_status=completed\n"
               "revision_task_owner=Wang\n"
               "revision_review_decision=needs_revision\n"
               "project_scaffold=deepseek-reliability-response-study\n"
               "project_scaffold_exports=json,markdown\n"
               "reserved_research_surface_checks=21\n"
               "usable_research_dataset_answers=0\n"
               "usable_research_dataset_cards=0\n"
               "usable_research_dataset_portfolios=0\n"
               "usable_research_dataset_previews=0\n"
               "usable_research_dataset_run_comparisons=0\n"
               "usable_research_dataset_runs=0\n"
               "usable_research_dataset_visualizations=0\n"
               "usable_research_evidence_syntheses=0\n"
               "usable_research_package_intakes=0\n"
               "usable_research_prisma_flows=0\n"
               "usable_research_project_action_executions=0\n"
               "usable_research_project_reviews=0\n"
               "usable_research_review_protocols=0\n"
               "usable_research_source_portfolios=0\n"
               "usable_research_study_protocol_bundles=0\n"
               "usable_research_study_protocol_compliance_reports=0\n"
               "usable_research_study_protocol_launches=0\n"
               "usable_research_study_protocol_runs=0\n"
               "usable_research_study_protocols=0\n"
               "usable_research_workbench_action_items=0\n"
               "usable_research_workbench_notes=0\n"
               "root_state_surface_checks=10\n"
               "root_projects=1\n"
               "root_runs=1\n"
               "root_reports=1\n"
               "root_plans=1\n"
               "root_search_records=2\n"
               "root_site_exports=1\n"
               "root_compare_profiles=1\n"
               "root_audit_records=5\n"
               "root_context_records=380\n"
               "root_project_id=lab-gene-x\n"
               "root_run_id=RUN-042\n"
               "root_report_id=RUN-042-recovery-report\n"
               "root_plan_id=PLAN-RUN-042-RECOVER-1\n"
               "root_search_id=search:1\n"
               "root_site_id=site:1\n"
               "root_compare_profile=agentcompare-default\n"
               "root_audit_spoof_denied=1\n"
			   "study_protocol_reproduction_checks=5\n"
			   "project_bundle_cache=ready\n"
			   "research_search_saved=2\n"
			   "project_surface_actions=4\n"
			   "study_protocol_checks=6\n"
			   "dataset_answer_files=4\n"
			   "package_intake_files=5\n"
			   "claim_records=8\n"
			   "provenance_paths=3\n"
			   "data_profiles=4\n"
			   "figure_records=3\n"
			   "trial_records=4\n"
			   "workflow_exports=5\n"
			   "workflow_portability_records=1\n"
			   "migration_steps=9\n"
			   "portability_rehearsal_cases=4\n"
			   "review_rounds=2\n"
			   "review_threads=2\n"
			   "review_action_items=2\n"
			   "data_versions=2\n"
			   "retry_attempts=2\n"
			   "relay_packets=3\n"
			   "llm_requests=3\n"
			   "llm_eval_passed=7\n"
			   "run_views=1\n"
			   "failure_items=1\n"
			   "poll_rounds=18\n"
			   "scanned_records=128\n"
			   "metric_files=151\n"
			   "ticks=42\n"
			   "status=ready\n")) {
		return 1;
	}
	if (!rp_write_file("rp_health",
			   "run_id=RUN-042\n"
			   "workers=4\n"
			   "healthy=4\n"
			   "budget=within_budget\n"
			   "failure_items=1\n"
			   "retry_attempts=2\n"
			   "view=ready\n"
			   "status=ready\n")) {
		return 1;
	}
	if (!rp_write_file("rp_agentcmp",
			   "case=user_on_plain_ucore\n"
			   "status=ready\n"
			   "coherence_checks=9\n"
			   "analysis_results_checks=96\n"
			   "decision_support_checks=80\n"
			   "scanned_records=128\n"
			   "poll_rounds=18\n"
			   "syscall_count=0\n"
			   "spoof_denied=0\n"
			   "context_trusted=0\n"
			   "audit_events=1\n"
			   "report_ok=1\n"
			   "repro_ok=1\n"
			   "llm_guarded=1\n"
			   "message_acks=35\n"
			   "tool_events=115\n"
			   "scheduler_items=21\n"
			   "ranked_tasks=21\n"
			   "selected_tasks=10\n"
			   "policy_checks=8\n"
			   "compliance=accepted\n"
			   "risk_items=3\n"
			   "capa_actions=2\n"
			   "risk_reviews=1\n"
			   "protocol_compliance_reports=1\n"
			   "protocol_amendments=1\n"
			   "sop_executions=1\n"
			   "decision_support_packets=1\n"
			   "delta_items=20\n"
			   "diff_records=1\n"
			   "timeline_events=9\n"
			   "worker_heartbeats=4\n"
			   "control_actions=8\n"
			   "run_config_profiles=2\n"
			   "workflow_invocations=1\n"
			   "workflow_attempts=12\n"
			   "completion_actions=4\n"
			   "consistency_checks=420\n"
			   "state_catalog_checks=12\n"
			   "startup_doctor_checks=14\n"
			   "host_state_keys=574\n"
			   "knowledge_index_checks=22\n"
			   "llm_transcript_checks=3\n"
			   "llm_bridge_transcripts=99\n"
			   "llm_bridge_requests=33\n"
			   "llm_bridge_responses=33\n"
			   "workbench_delivery_checks=15\n"
			   "usable_research_workbenches=8\n"
			   "usable_research_templates=8\n"
			   "usable_research_workspace_imports=9\n"
			   "usable_research_workspace_inspections=9\n"
			   "usable_research_workbench_answers=11\n"
			   "usable_research_deliveries=9\n"
			   "usable_research_studio_sessions=2\n"
			   "usable_research_project_action_plans=17\n"
			   "usable_research_project_deliveries=4\n"
			   "usable_research_project_runbooks=17\n"
			   "usable_research_project_evidence_audits=17\n"
			   "usable_research_project_provenance_graphs=4\n"
			   "usable_research_project_launches=3\n"
			   "usable_research_project_release_gates=17\n"
			   "usable_research_project_snapshots=17\n"
			   "search_documents=1685\n"
			   "provenance_nodes=406\n"
			   "provenance_links=544\n"
			   "event_stream_records=8966\n"
			   "context_records=380\n"
			   "host_workflow_artifacts=150\n"
			   "usable_research_artifacts=507\n"
			   "usable_research_runs=23\n"
			   "usable_research_stages=197\n"
			   "usable_research_messages=265\n"
			   "usable_research_decisions=242\n"
			   "coherence_checks=9\n"
			   "namespace_checks=12\n"
			   "surface_checks=13\n"
			   "status_semantics=11\n"
			   "reference_checks=18\n"
			   "evidence_trace_checks=14\n"
			   "run_state_checks=9\n"
			   "lifecycle_checks=10\n"
			   "delivery_coherence=3\n"
			   "agentos_readiness_checks=7\n"
			   "runner_stages=5\n"
			   "runner_retries=1\n"
			   "runner_cache_hits=1\n"
			   "workflow_runner_files=5\n"
			   "workflow_events=8\n"
			   "workflow_manifest_records=4\n"
			   "workbench_records=10\n"
			   "workbench_tasks=9\n"
			   "dynamic_input_records=8\n"
			   "dynamic_submissions=4\n"
			   "host_ui_events=10\n"
			   "artifact_records=2\n"
			   "data_pipeline_files=6\n"
			   "dataset_snapshots=2\n"
			   "data_previews=2\n"
			   "data_quality_checks=7\n"
			   "data_transforms=2\n"
			   "dataset_collection_items=4\n"
			   "relay_protocol_files=5\n"
			   "relay_routes=4\n"
			   "host_request_files=1\n"
			   "fallback_cases=1\n"
			   "agent_roles=7\n"
			   "collaboration_decisions=8\n"
			   "handoffs=6\n"
			   "deliberation_items=5\n"
			   "backend_cases=7\n"
			   "bio_service_files=5\n"
			   "bio_samples=8\n"
			   "bio_aliquots=12\n"
			   "lab_resource_files=5\n"
			   "lab_governance_ops_checks=26\n"
			   "approval_checks=2\n"
			   "ethics_protocol_checks=1\n"
			   "protocol_governance_checks=4\n"
			   "sop_execution_checks=3\n"
			   "training_record_checks=4\n"
			   "instrument_maintenance_checks=3\n"
			   "inventory_transaction_checks=3\n"
			   "procurement_order_checks=2\n"
			   "resource_budget_checks=2\n"
			   "run_queue_checks=1\n"
			   "notification_checks=1\n"
			   "instrument_count=4\n"
			   "inventory_items=9\n"
			   "publication_service_files=5\n"
			   "result_review_items=10\n"
			   "fair_checks=8\n"
			   "knowledge_service_files=5\n"
			   "semantic_documents=17\n"
			   "knowledge_answers=4\n"
			   "runtime_service_files=5\n"
			   "runtime_envs=4\n"
			   "notebook_cells=8\n"
			   "notebook_exports=2\n"
			   "downloadable_units=4\n"
			   "startup_checks=8\n"
			   "platform_doctor_checks=10\n"
			   "secret_values_written=0\n"
			   "runtime_assurance_checks=24\n"
			   "secret_reference_checks=6\n"
			   "model_registry_checks=5\n"
			   "llm_proxy_replay_audits=2\n"
			   "collaboration_threads=2\n"
			   "collaboration_action_items=2\n"
			   "observability_alerts=5\n"
			   "observability_health_reports=1\n"
			   "research_ops_checks=28\n"
			   "semantic_graph_checks=6\n"
			   "prompt_ops_checks=5\n"
			   "runbook_checks=7\n"
			   "worker_ops_checks=5\n"
			   "execution_control_checks=5\n"
			   "regulated_research_checks=32\n"
			   "annotation_checks=5\n"
			   "assay_plate_checks=4\n"
			   "cohort_monitoring_checks=3\n"
			   "data_access_checks=4\n"
			   "research_card_checks=4\n"
			   "research_object_checks=5\n"
			   "sample_custody_checks=3\n"
			   "statistical_design_checks=2\n"
			   "workflow_template_checks=2\n"
			   "research_product_checks=18\n"
			   "project_scaffold_files=8\n"
			   "dataset_product_exports=9\n"
			   "dataset_product_runs=2\n"
			   "source_portfolio_exports=1\n"
			   "research_portfolio_checks=16\n"
			   "usable_research_sources=67\n"
			   "usable_research_datasets=5\n"
			   "usable_research_literature_searches=7\n"
			   "usable_research_reviews=11\n"
			   "usable_research_evidence_reviews=7\n"
			   "usable_research_evidence_extractions=25\n"
			   "usable_research_screening_decisions=25\n"
			   "usable_research_exports=80\n"
			   "usable_research_platform_doctor_reports=12\n"
			   "usable_research_project_handoff_audits=34\n"
			   "usable_research_project_run_comparisons=17\n"
			   "usable_research_project_reproducibility_audits=17\n"
			   "usable_research_project_snapshot_comparisons=17\n"
			   "execution_scale_checks=14\n"
			   "host_workflow_runs=10\n"
			   "host_workflow_stage_runs=70\n"
			   "host_workflow_cache=6\n"
			   "host_agent_messages=70\n"
			   "host_agent_decisions=70\n"
			   "agentcompare_reports=4\n"
			   "agentcompare_results=20\n"
			   "agentcompare_profiles=1\n"
			   "content_objects=129\n"
			   "object_references=129\n"
			   "operations_scale_checks=12\n"
			   "host_audit_records=5\n"
			   "host_metrics=13\n"
			   "host_llm_providers=3\n"
			   "host_secret_references=3\n"
			   "host_executed_corr_ids=4\n"
			   "usable_research_projects=23\n"
			   "host_artifacts=128\n"
			   "host_messages=70\n"
			   "host_content_objects=129\n"
			   "host_object_references=129\n"
			   "host_agentcompare_reports=4\n"
			   "host_agentcompare_results=20\n"
               "project_revision_incident_checks=12\n"
               "usable_research_revision_tasks=1\n"
               "usable_research_project_scaffolds=1\n"
               "incidents=1\n"
               "incident_id=INC-RUN-042-ALIGN-OOM\n"
               "incident_failed_stage=align\n"
               "incident_reason=memory_limit\n"
               "incident_status=closed\n"
               "revision_task_status=completed\n"
               "revision_task_owner=Wang\n"
               "revision_review_decision=needs_revision\n"
               "project_scaffold=deepseek-reliability-response-study\n"
               "project_scaffold_exports=json,markdown\n"
               "reserved_research_surface_checks=21\n"
               "usable_research_dataset_answers=0\n"
               "usable_research_dataset_cards=0\n"
               "usable_research_dataset_portfolios=0\n"
               "usable_research_dataset_previews=0\n"
               "usable_research_dataset_run_comparisons=0\n"
               "usable_research_dataset_runs=0\n"
               "usable_research_dataset_visualizations=0\n"
               "usable_research_evidence_syntheses=0\n"
               "usable_research_package_intakes=0\n"
               "usable_research_prisma_flows=0\n"
               "usable_research_project_action_executions=0\n"
               "usable_research_project_reviews=0\n"
               "usable_research_review_protocols=0\n"
               "usable_research_source_portfolios=0\n"
               "usable_research_study_protocol_bundles=0\n"
               "usable_research_study_protocol_compliance_reports=0\n"
               "usable_research_study_protocol_launches=0\n"
               "usable_research_study_protocol_runs=0\n"
               "usable_research_study_protocols=0\n"
               "usable_research_workbench_action_items=0\n"
               "usable_research_workbench_notes=0\n"
               "root_state_surface_checks=10\n"
               "root_projects=1\n"
               "root_runs=1\n"
               "root_reports=1\n"
               "root_plans=1\n"
               "root_search_records=2\n"
               "root_site_exports=1\n"
               "root_compare_profiles=1\n"
               "root_audit_records=5\n"
               "root_context_records=380\n"
               "root_project_id=lab-gene-x\n"
               "root_run_id=RUN-042\n"
               "root_report_id=RUN-042-recovery-report\n"
               "root_plan_id=PLAN-RUN-042-RECOVER-1\n"
               "root_search_id=search:1\n"
               "root_site_id=site:1\n"
               "root_compare_profile=agentcompare-default\n"
               "root_audit_spoof_denied=1\n"
			   "study_protocol_reproduction_checks=5\n"
			   "project_bundle_cache=ready\n"
			   "claim_records=8\n"
			   "provenance_paths=3\n"
			   "data_profiles=4\n"
			   "figure_records=3\n"
			   "trial_records=4\n"
			   "workflow_exports=5\n"
			   "workflow_portability_records=1\n"
			   "migration_steps=9\n"
			   "portability_rehearsal_cases=4\n"
			   "review_rounds=2\n"
			   "review_threads=2\n"
			   "review_action_items=2\n"
			   "data_versions=2\n"
			   "retry_attempts=2\n"
			   "relay_packets=3\n"
			   "llm_requests=3\n"
			   "llm_eval_passed=7\n"
			   "run_views=1\n"
			   "health_ok=1\n"
			   "ticks=42\n"
			   "status=ready\n")) {
		return 1;
	}
	if (rp_host_seed_has("kind=research_run")) {
		char seed_run[48];
		if (!rp_host_seed_copy_value_for_kind("kind=research_run", "run_id=", seed_run, sizeof(seed_run))) {
			rp_copy_text(seed_run, sizeof(seed_run), "RUN-905");
		}
		if (!rp_append_host_action_line("rp_agentcmp", "host_action_research_run=usable-run:", seed_run)) return 1;
		if (!rp_append_file("rp_agentcmp", "host_action_research_input=ready")) return 1;
	}
	if (rp_host_seed_has("kind=agentcompare")) {
		char profile[48];
		if (!rp_host_seed_copy_value_for_kind("kind=agentcompare", "profile=", profile, sizeof(profile))) {
			rp_copy_text(profile, sizeof(profile), "plain_ucore");
		}
		if (!rp_append_file("rp_agentcmp", "host_action_compare_requested=1")) return 1;
		if (!rp_append_host_action_line("rp_agentcmp", "host_action_compare_profile=", profile)) return 1;
	}
	if (rp_host_seed_has("kind=human_review")) {
		if (!rp_append_file("rp_agentcmp", "host_action_review_requested=1")) return 1;
	}
	if (rp_host_seed_has("kind=revision_task") || rp_host_seed_has("kind=revision_run")) {
		if (!rp_append_file("rp_agentcmp", "host_action_revision_requested=1")) return 1;
	}
	if (rp_host_seed_has("kind=workbench") ||
	    rp_host_seed_has("kind=workbench_complete") ||
	    rp_host_seed_has("kind=workbench_advance") ||
	    rp_host_seed_has("kind=workbench_auto_advance") ||
	    rp_host_seed_has("kind=workbench_task") ||
	    rp_host_seed_has("kind=workbench_note") ||
	    rp_host_seed_has("kind=workbench_notes") ||
	    rp_host_seed_has("kind=workbench_handoff_package") ||
	    rp_host_seed_has("kind=workbench_readiness") ||
	    rp_host_seed_has("kind=workbench_answer") ||
	    rp_host_seed_has("kind=workbench_answer_audit") ||
	    rp_host_seed_has("kind=workbench_evidence_search") ||
	    rp_host_seed_has("kind=workbench_brief") ||
	    rp_host_seed_has("kind=workbench_evidence_dossier") ||
	    rp_host_seed_has("kind=workbench_evidence_graph") ||
	    rp_host_seed_has("kind=workbench_citations") ||
	    rp_host_seed_has("kind=workbench_manuscript") ||
	    rp_host_seed_has("kind=workbench_manuscript_audit") ||
	    rp_host_seed_has("kind=workbench_manuscript_revision_plan") ||
	    rp_host_seed_has("kind=workbench_manuscript_revision_task") ||
	    rp_host_seed_has("kind=workbench_task_board") ||
	    rp_host_seed_has("kind=workbench_task_board_row") ||
	    rp_host_seed_has("kind=workbench_runbook") ||
	    rp_host_seed_has("kind=workbench_timeline") ||
	    rp_host_seed_has("kind=workbench_file_manifest") ||
	    rp_host_seed_has("kind=workbench_file_verify") ||
	    rp_host_seed_has("kind=workbench_export")) {
		if (!rp_append_file("rp_agentcmp", "host_action_workbench_requested=1")) return 1;
	}
	if (rp_host_seed_has("kind=bundle_export") ||
	    rp_host_seed_has("kind=research_export") ||
	    rp_host_seed_has("kind=notebook_export")) {
		if (!rp_append_file("rp_agentcmp", "host_action_export_requested=1")) return 1;
	}
	if (!rp_append_file("rp_ack", "ack=metrics;msg=14;status=ready")) return 1;
	if (!rp_append_file("rp_tool", "tool=metrics.measure_plain")) return 1;
	if (!rp_append_file("rp_tool", "tool=metrics.write_health")) return 1;
	if (!rp_append_status("telemetry=ready")) return 1;
	if (!rp_append_status("agentcmp=ready")) return 1;
	if (!rp_append_status("health=ready")) return 1;
	printf("rp_metrics: telemetry_spans=8 acks=35 tools=115 services=25 lab_governance=26 products=18 assurance=24 research_ops=28 regulated=32 state_catalog=12 startup_doctor=14 knowledge_index=22 llm_transcripts=3 workbench_delivery=15 portfolio_scale=16 execution_scale=14 operations_scale=12 project_revision_incident=12 reserved_surfaces=21 root_state=10 agentos_reserved=21 delta_items=20 dynamic=4 status=ready\n");
	return 0;
}
